### ISSUE TITLE
keys that should be valid ArchieML

### ISSUE THREAD

**Issue by tschaume** [brainkim/archieml-python#12]
The following key-value pairs are successfully parsed in the ArchieML sandbox but don't convert into a dict via `archieml.loads()`. It looks like the `KEY_PATTERN` regex isn't covering them.

```
a/b: 5
a(b): 1e+16 cm⁻³
Σ_(ms)⁻¹.κₑ_W/(mKs): 10
```

**Comment by brainkim** [comment]
@tschaume The pull request caused some tests to fail; will try to take a deeper look at this issue soon! Thanks!

**Comment by brainkim** [comment]
Got your changes back in, but had to fix multiline escape lines or something. Thanks again!
