### ISSUE TITLE
Logic behind array-closing markers ([]) is broken

### ISSUE THREAD

**Issue by adrian-the-git** [brainkim/archieml-python#6]
The following valid ArchieML doesn't parse correctly:

```
[a]
* first
[b]
* second
[]
c: No more parsing?
```

However this is fine:

```
[a]
* first
[]
[b]
* second
[]
c: This is just fine.
```

Presumably the logic behind closing arrays needs to work backward and close all the "open" ones. I'll have a look at the code and see if I can fix it, but maybe someone will beat me to it.

**Comment by brainkim** [comment]
Should be fixed in latest! Forgot to close!
