### ISSUE TITLE
only archieml-0.1.0 available on PyPI

### ISSUE THREAD

**Issue by tschaume** [brainkim/archieml-python#7]
`pip install archieml` still installs version 0.1.0 instead of 0.3.0! Probably due to the missing archive for 0.3.0, c.f. https://pypi.python.org/pypi/archieml/0.1.0 vs https://pypi.python.org/pypi/archieml/0.3.0

**Comment by brainkim** [comment]
Fixed maybe? Ugh I'm so sorry. I worked in a python shop but never had to distribute libraries, and pypi seems kinda crufty to me. Fixed I think.

**Comment by tschaume** [comment]
Yes, fixed. Thanks!
