### ISSUE TITLE
Parser doesn't handle non-ascii correctly

### ISSUE THREAD

**Issue by bochecha** [brainkim/archieml-python#8]
Consider this very simple example:

```python
>>> s1 = """question: Pourquoi ?
... réponse: Parce que."""
... 
>>> archieml.loads(s1)
OrderedDict([('question', 'Pourquoi ?')])
```

That's not right.

The [ArchieML sandbox](http://archieml.org/sandbox.html) does it correctly, displaying:

```
{
  "question": "Pourquoi ?",
  "réponse": "Parce que."
}
```

**Comment by brainkim** [comment]
Looks great! My bad I think I just adapted the regexes from the javascript version. I'll try to merge and cut a release soon.
